project:
  type: book

book:
  title: "Cyber2A training curriculum for Arctic-AI research"
  author: "to include"
  date: "8/22/2023"
  chapters:
    - index.qmd
    - sections/topic-1-AI-ready-training-datasets.qmd
    - sections/topic-2-AI-model-building.qmd
    - sections/topic-3-workflow-validation.qmd
    - sections/topic-4-model-explainability.qmd
    - sections/topic-5-model-deployment.qmd  
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo



