project:
  type: book
  output-dir: _book

book:
  title: "Cyber2A training curriculum for Arctic-AI research **~ DRAFT ~**"
  author: "to include"
  date: "10/16/2023"
  search: true
  favicon: images/index/arcticlogo.png
  chapters:
    - index.qmd
    - part: "<b>Introduction to AI and Arctic Science</b>"
      chapters:
        - sections/breaking-the-ice-with-ai-in-arctic-science.qmd
        - sections/ai-for-everyone.qmd
        - sections/guest-lecture-anna-chandi.qmd
        - sections/the-fun-and-frontiers-of-ai.qmd

    - part: "<b>Data Management and Preparation for AI</b>"
      chapters:  
        - sections/ai-ready-data-in-arctic-research.qmd
        - sections/guest-lecture-yili-arts-dataset.qmd
        - sections/data-annotation.qmd
        - sections/hands-on-lab-data-annotation.qmd    
    
    - part: "<b>AI Fundamentals and Techniques</b>"
      chapters:
        - sections/the-building-blocks-of-nn-and-dl.qmd
        - sections/intro-to-pytorch.qmd
        - sections/hands-on-lab-pytorch.qmd
        - sections/exploring-advanced-neural-networks.qmd
        - sections/intro-to-dl-libraries-for-image-analysis.qmd
        - sections/hands-on-lab-mmsegmentation.qmd

    - part: "<b>Advanced AI Workflows and Models</b>"
      chapters:
        - sections/ai-workflows-and-mlops.qmd
        - sections/hands-on-lab-ai-workflows.qmd
        - sections/foundation-models.qmd
        - sections/hands-on-lab-foundation-models.qmd
    
    - part: "<b>Ethics and Social Implications of AI</b>"
      chapters:
        - sections/ai-ethics.qmd
        - sections/socially-responsible-ai.qmd
        - sections/reproducibility.qmd
    
  sidebar:
    tools:
      - icon: house-door-fill
        href: https://cyber2a.github.io
        aria-label: Cyber2A Homepage
      - icon: twitter
        href: https://twitter.com/cyber2a_nsf
        aria-label: Twitter
      - icon: github
        href: https://github.com/cyber2a/cyber2a-course
        aria-label: GitHub

bibliography: references.bib

format:
  html:
    theme: cosmo



