project:
  type: book
  output-dir: _book

book:
  title: "Cyber2A training curriculum for Arctic-AI research **~ DRAFT ~**"
  author: "to include"
  date: "10/16/2023"
  search: true
  favicon: images/index/arcticlogo.png
  chapters:
    - index.qmd
    - sections/intro-to-neural-networks.qmd
    - sections/retrogressive-thaw-slumps.qmd
    - sections/intro-to-pytorch.qmd
    - sections/pytorch-hands-on-lab.qmd
    - sections/AI-ready-training-datasets.qmd    
    - sections/data-anotation-for-deep-learning.qmd
    - sections/u-net-for-semanting-segmentation.qmd
    - sections/u-net-lab.qmd
    - sections/model-explainability.qmd
    - sections/intro-to-mmsegmentation.qmd
    - sections/mmsegmentation-hands-on-lab.qmd
    - sections/model-deployment.qmd
    - sections/data-ethics.qmd
    - sections/popular-models-and-applications.qmd
    - references.qmd
  sidebar:
    tools:
      - icon: house-door-fill
        href: https://cyber2a.github.io
        aria-label: Cyber2A Homepage
      - icon: twitter
        href: https://twitter.com/cyber2a_nsf
        aria-label: Twitter
      - icon: github
        href: https://github.com/cyber2a/cyber2a-course
        aria-label: GitHub

bibliography: references.bib

format:
  html:
    theme: cosmo



