project:
  type: book
  output-dir: _book

book:
  title: "Cyber2A training curriculum for Arctic-AI research **~ DRAFT ~**"
  author: "to include"
  date: "10/16/2023"
  search: true
  favicon: images/index/arcticlogo.png
  chapters:
    - index.qmd
    - sections/intro-to-neural-networks.qmd
    - sections/AI-ready-training-datasets.qmd
    #- sections/topic-2-AI-model-building.qmd
    #- sections/topic-3-workflow-validation.qmd
    #- sections/topic-4-model-explainability.qmd
    #- sections/topic-5-model-deployment.qmd  
    - references.qmd
  sidebar:
    tools:
      - icon: house-door-fill
        href: https://cyber2a.github.io
        aria-label: Cyber2A Homepage
      - icon: twitter
        href: https://twitter.com/cyber2a_nsf
        aria-label: Twitter
      - icon: github
        href: https://github.com/cyber2a/cyber2a-course
        aria-label: GitHub

bibliography: references.bib

format:
  html:
    theme: cosmo



