project:
  type: book
  output-dir: _book

book:
  title: "Cyber2A training curriculum for Arctic-AI research **~ DRAFT ~**"
  author: "to include"
  date: "10/16/2023"
  search: true
  favicon: images/index/arcticlogo.png
  chapters:
    - index.qmd
    - sections/breaking-the-ice-with-ai-in-arctic-science.qmd
    - sections/ai-for-everyone.qmd
    - sections/ai-ready-data-in-arctic-research.qmd
    - sections/data-annotation.qmd
    - sections/hands-on-lab-data-annotation.qmd    
    - sections/the-building-blocks-of-nn-and-dl.qmd
    - sections/intro-to-pytorch.qmd
    - sections/hands-on-lab-pytorch.qmd
    - sections/exploring-advanced-neural-networks.qmd
    - sections/intro-to-dl-libraries-for-image-analysis.qmd
    - sections/hands-on-lab-detectron2.qmd
    - sections/ai-workflows-and-mlops.qmd
    - sections/hands-on-lab-ai-workflows.qmd
    - sections/foundation-models.qmd
    - sections/hands-on-lab-foundation-models.qmd
    - sections/ai-ethics.qmd
    - sections/socially-responsible-ai.qmd
    - sections/reproducibility.qmd
    - sections/the-fun-and-frontiers-of-ai.qmd
    - references.qmd
  sidebar:
    tools:
      - icon: house-door-fill
        href: https://cyber2a.github.io
        aria-label: Cyber2A Homepage
      - icon: twitter
        href: https://twitter.com/cyber2a_nsf
        aria-label: Twitter
      - icon: github
        href: https://github.com/cyber2a/cyber2a-course
        aria-label: GitHub

bibliography: references.bib

format:
  html:
    theme: cosmo



